name: Run API Automation Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run Cypress tests and generate Mochawesome report
              run: npm run test:run

            # - name: Upload HTML Report Artifact
            #   uses: actions/upload-artifact@v3
            #   with:
            #       name: mochawesome-report
            #       path: cypress/reports/html
